services:
  db:
    image: postgres
    container_name: connected-minds-db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=connected_minds_db

    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db: