spring.application.name=connected-minds-api


## Database
spring.datasource.url=jdbc:postgresql://localhost:5432/connected-minds-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver


## JWT
jwt.secret.key=secret