spring.application.name=connected-minds-api


## Database
spring.datasource.url=jdbc:postgresql://localhost:5432/connected_minds_db
spring.datasource.username=postgres
spring.datasource.password=postgres

## JPA
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


## JWT
jwt.secret.key=secret