springdoc:
  swagger-ui:
    path: /docs/ui
  api-docs:
    path: /docs
spring:
  application:
      name: connected-minds-api
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    secret-key: secret
    origin-url: http://localhost:3000